import Link from 'next/link'
import React from 'react'
import Head from 'next/head'

const TShirts = () => {
  return (
    <div>

      <Head>
        <title>Wellcome to T - Shirt's Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32-32.png"/>
      </Head>

      <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
          <div class="flex flex-wrap -m-4">
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full cursor-pointer shadow-lg rounded-3xl ">  {/* IF YPU WANT GIVE M-5 FOR MARGIN */}
              <Link class="block relative rounded overflow-hidden" href={'/product/TShirts'}>
                <img alt="ecommerce" class=" m-auto h-[36vh] block" src="https://m.media-amazon.com/images/I/61iWM4s4XCL._AC_UL320_.jpg" />
                  </Link>
              <div class="mt-4 text-center">
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                <h2 class="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
                <p class="mt-1">₹ 16.00</p>
                <p class="mt-1">S , M , L , XL , XXL</p>
            </div>
          </div>

          <div class="lg:w-1/4 md:w-1/2 p-4 w-full cursor-pointer shadow-lg rounded-3xl ">  {/* IF YPU WANT GIVE M-5 FOR MARGIN */}
            <a class="block relative rounded overflow-hidden">
              <img alt="ecommerce" class=" m-auto h-[36vh] block" src="https://m.media-amazon.com/images/I/61iWM4s4XCL._AC_UL320_.jpg" />
            </a>

          <div class="mt-4 text-center">
            <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
            <h2 class="text-gray-900 title-font text-lg font-medium">Shooting Stars</h2>
            <p class="mt-1">₹ 21.15</p>
            <p class="mt-1">S , M , L , XL , XXL</p>
          </div>
        </div>

        <div class="lg:w-1/4 md:w-1/2 p-4 w-full cursor-pointer shadow-lg rounded-3xl ">  {/* IF YPU WANT GIVE M-5 FOR MARGIN */}
          <a class="block relative rounded overflow-hidden">
            <img alt="ecommerce" class=" m-auto h-[36vh] block" src="https://m.media-amazon.com/images/I/61iWM4s4XCL._AC_UL320_.jpg" />
          </a>
        <div class="mt-4 text-center">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium">Neptune</h2>
          <p class="mt-1">₹ 12.00</p>
          <p class="mt-1">S , M , L , XL , XXL</p>
        </div>
      </div>
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full cursor-pointer shadow-lg rounded-3xl ">  {/* IF YPU WANT GIVE M-5 FOR MARGIN */}
        <a class="block relative rounded overflow-hidden">
          <img alt="ecommerce" class=" m-auto h-[36vh] block" src="https://m.media-amazon.com/images/I/61iWM4s4XCL._AC_UL320_.jpg" />
        </a>
        <div class="mt-4 text-center">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium">The 400 Blows</h2>
          <p class="mt-1">₹ 18.40</p>
          <p class="mt-1">S , M , L , XL , XXL</p>
        </div>
      </div>
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full cursor-pointer shadow-lg rounded-3xl ">  {/* IF YPU WANT GIVE M-5 FOR MARGIN */}
        <a class="block relative rounded overflow-hidden">
          <img alt="ecommerce" class=" m-auto h-[36vh] block" src="https://m.media-amazon.com/images/I/61iWM4s4XCL._AC_UL320_.jpg" />
        </a>
        <div class="mt-4 text-center">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
          <p class="mt-1">₹ 16.00</p>
          <p class="mt-1">S , M , L , XL , XXL</p>
        </div>
      </div>
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full cursor-pointer shadow-lg rounded-3xl ">  {/* IF YPU WANT GIVE M-5 FOR MARGIN */}
        <a class="block relative rounded overflow-hidden">
          <img alt="ecommerce" class=" m-auto h-[36vh] block" src="https://m.media-amazon.com/images/I/61iWM4s4XCL._AC_UL320_.jpg" />
        </a>
        <div class="mt-4 text-center">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium">Shooting Stars</h2>
          <p class="mt-1">₹ 21.15</p>
          <p class="mt-1">S , M , L , XL , XXL</p>
        </div>
      </div>
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full cursor-pointer shadow-lg rounded-3xl ">  {/* IF YPU WANT GIVE M-5 FOR MARGIN */}
        <a class="block relative rounded overflow-hidden">
          <img alt="ecommerce" class="m-auto h-[36vh] block" src="https://m.media-amazon.com/images/I/61iWM4s4XCL._AC_UL320_.jpg" />
        </a>
        <div class="mt-4 text-center">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium">Neptune</h2>
          <p class="mt-1">₹ 12.00</p>
          <p class="mt-1">S , M , L , XL , XXL</p>
        </div>
      </div>
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full cursor-pointer shadow-lg rounded-3xl ">  {/* IF YPU WANT GIVE M-5 FOR MARGIN */}
        <a class="block relative rounded overflow-hidden">
          <img alt="ecommerce" class=" m-auto h-[36vh] block" src="https://m.media-amazon.com/images/I/61iWM4s4XCL._AC_UL320_.jpg" />
        </a>
        <div class="mt-4 text-center">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium">The 400 Blows</h2>
          <p class="mt-1">₹ 18.40</p>
          <p class="mt-1">S , M , L , XL , XXL</p>
        </div>
      </div>
    </div>
  </div>
</section>
    </div>
  )
}

export default TShirts